server:
  port: 8091
spring:
  application:
    name: identity-security-management
  data:
    mongodb:
      uri: mongodb+srv://moderator:1s89026mS4Hp7eNZ@db-mongodb-blr1-vms-59c60299.mongo.ondigitalocean.com/identityManagement?tls=true&authSource=admin&replicaSet=db-mongodb-blr1-vms
     # uri: mongodb://localhost:27017/compliance_management_db
      socketTimeout: 60000
      connectTimeout: 60000
      serverSelectionTimeout: 60000
    redis:
      host: 139.59.67.255
      port: 6379
      password: work4uneo

# Email API configuration
email:
  api:
    base-url: http://139.59.67.255:8093/communication/emails

eureka:
  instance:
    preferIpAddress: true
    ip-address: ${IDENTITY_IP:localhost}
  client:
    tls:
      enabled: true
      trust-store: classpath:certs/compliance-gateway-truststore.p12
      trust-store-password: passw0rd
      trust-store-type: PKCS12
      key-store: classpath:certs/compliance-gateway-truststore.p12
      key-store-password: passw0rd
      key-store-type: PKCS12
    serviceUrl:
      defaultZone: https://139.59.67.255:8761/eureka/
      #defaultZone: https://localhost:8761/eureka/

security:
  app:
    jwtCookieName: neocompliance
    jwtSecret: ${JWT_SECRET:3neo38792F423F4428472B4B6250655368566D597133743677397A244326test}
    jwtExpirationMs: 86400000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.in: DEBUG
  file:
    name: /root/webapp/identity-management.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
